spring:
  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/moviedb

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
project:
  poster: posters/

base:
  url: "http://localhost:8080"
